#!/bin/sh

. /lib/functions/gl_util.sh

/etc/init.d/rtty enable

uci set rtty.general=rtty
uci set rtty.general.id="$(get_default_sn)"
uci set rtty.general.description="$(get_model)"
uci set rtty.general.onlyid="$(date +%s)"
uci set rtty.general.host="rtty.hicloud.org"
uci set rtty.general.token="6f4eb9a44902dec8e70ace48df0dbc68"
uci set rtty.general.password="73846d4f9c7c4e3f"
uci set rtty.general.ssl=1
uci set rtty.general.ssh_en=1
uci set rtty.general.web_en=1
uci commit rtty

if [ -z "$(grep uci_load_validate /lib/functions/procd.sh)" ]; then
    cat >>/mnt/functions/procd.sh <<EOF
uci_load_validate() {
	local _package="\$1"
	local _type="\$2"
	local _name="\$3"
	local _function="\$4"
	local _option
	local _result
	shift; shift; shift; shift
	for _option in "\$@"; do
		eval "local \${_option%%:*}"
	done
	uci_validate_section "\$_package" "\$_type" "\$_name" "\$@"
	_result=\$?
	[ -n "\$_function" ] || return \$_result
	eval "\$_function \"\\\$_name\" \"\\\$_result\""
}
EOF
fi
