#!/bin/sh

get_model() {
	local board boardname

	. /lib/functions.sh

	board=$(board_name)
	boardname="${board#*-}"

	[ -n "$boardname" ] || {
		loger "Unsupported model (model not in support-list)"
		echo ""
		return
	}
	if [ "$board" = "glinet,mt2500-emmc"] 
	then
		boardname="mt2500"
	fi
	case "$boardname" in
	"ar300m-nor" | \
		'ar300m-nand')
		echo "ar300m"
		;;
	"ar750s-nor" | \
		"ar750s-nor-nand")
		echo "ar750s"
		;;
	"e750-nor" | \
		"e750-nor-nand")
		echo "e750"
		;;
	"x750-nor" | \
		"x750-nor-nand")
		echo "x750"
		;;
	"x300b-nor" | \
		"x300b-nor-nand")
		echo "x300b"
		;;
	"xe300-iot" | \
		"xe300-nor" | \
		"xe300-nor-nand")
		echo "xe300"
		;;
	"x1200-nor" | \
		"x1200-nor-nand")
		echo "x1200"
		;;
	"s200-nor" | \
		"s200-nor-nand")
		echo "s200"
		;;
	"01-16m")
		echo "Smart-4G"
		;;
	*)
		echo "$boardname"
		;;
	esac
}
get_default_sn() {
	local sn model mtd skip

	skip=0x0

	model=$(get_model)
	case $model in
	"b1300" | \
		"b2200" | \
		"ap1300" | \
		"s1300")
		mtd="mtd7"
		skip=0x30
		;;
	"ax1800")
		mtd="$(cat /tmp/art_mtd)"
		skip=$((0x40))
		;;
	"usb150" | \
		"inet" | \
		"ar150" | \
		"ar300m" | \
		"mifi" | \
		"ar750" | \
		"ar750s" | \
		"e750" | \
		"x750" | \
		"x300b" | \
		"x1200")
		mtd=$(cat /proc/mtd | awk -F: '/art/{print $1}')
		skip=0x30
		;;
	"mt300a" | \
		"mt300n" | \
		"vixmini" | \
		"n300" | \
		"mt1300" | \
		"mt300n-v2")
		mtd="mtd2"
		skip=0x4030
		;;
	"mv1000")
		mtd="mtd2"
		skip=0x30
		;;
	"sf1200" | \
		"sft1200")
		mtd="mtd3"
		skip=0x430
		;;
	"mt2500")
		sn=$(cat /proc/gl-hw-info/device_sn)
		;;
	*)
		mac=$(cat /sys/class/net/eth0/address)
		sn=$(echo 'hitosea'${mac}${model} | md5sum | awk '{print substr($1,1,16)}')
		;;
	esac

	[ -z "$sn" ] && sn=$(hexdump -v -n 16 -s $((0x0 + $skip)) -e '16/16 "%s"' /dev/$mtd)

	echo "$sn"
}

/etc/init.d/rtty enable

[ -z "$(uci get rtty.general.onlyid)" ] && {
	uci set rtty.general=rtty
	uci set rtty.general.id="$(get_default_sn)"
	uci set rtty.general.description="$(get_model)"
	uci set rtty.general.onlyid="$(head /dev/urandom | md5sum | cut -c 1-8)"
	uci set rtty.general.host="router.api.gezi.vip"
	uci set rtty.general.token="6f4eb9a44902dec8e70ace48df0dbc68"
	uci set rtty.general.password="73846d4f9c7c4e3f"
	uci set rtty.general.ssl=1
	uci set rtty.general.ssh_en=1
	uci set rtty.general.web_en=1
	uci commit rtty
}

if [ -z "$(grep uci_load_validate /lib/functions/procd.sh)" ]; then
	cat >>/lib/functions/procd.sh <<EOF
uci_load_validate() {
	local _package="\$1"
	local _type="\$2"
	local _name="\$3"
	local _function="\$4"
	local _option
	local _result
	shift; shift; shift; shift
	for _option in "\$@"; do
		eval "local \${_option%%:*}"
	done
	uci_validate_section "\$_package" "\$_type" "\$_name" "\$@"
	_result=\$?
	[ -n "\$_function" ] || return \$_result
	eval "\$_function \"\\\$_name\" \"\\\$_result\""
}
EOF
fi
/etc/init.d/rtty start
