#!/bin/sh

. /lib/functions/gl_util.sh

/etc/init.d/rtty enable

uci set rtty.general=rtty
uci set rtty.general.id="$(get_default_sn)"
uci set rtty.general.description="$(get_model)"
uci set rtty.general.onlyid="$(date +%s)"
uci set rtty.general.host="rtty.hicloud.org"
uci set rtty.general.token="6f4eb9a44902dec8e70ace48df0dbc68"
uci set rtty.general.password="73846d4f9c7c4e3f"
uci set rtty.general.ssl=1
uci set rtty.general.ssh_en=1
uci set rtty.general.web_en=1
uci commit rtty