name: glinet-build
on:
  push:
    tags:
      - "cloud7*"
    
  
env:
  REPO_URL: https://github.com/innet8/rtty.git
  REPO_BRANCH: hi-openwrt-package

jobs:
  build:
    name: Build ${{ matrix.arch }} ipk
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - ipq_ipq60xx-qsdk11
          - ipq807x-2102

    steps:
      - uses: actions/checkout@v3
      - run: sed -i 's/router.api.speedbox.ink/router.api.gezi.vip/g' $GITHUB_WORKSPACE/files/99-rtty
      - name: Build
        uses: innet8/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          MODE: glinet
          DEPENDENCES: libev libopenssl libmbedtls zlib
          ADDR: ${{ env.REPO_URL }}
          BRANCH: ${{ env.REPO_BRANCH }}
          PKG: rtty

      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: "rtty*.ipk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
