name: snapshots-build
on: workflow_dispatch
env:
  REPO_URL: https://github.com/innet8/rtty.git
  REPO_BRANCH: hi-openwrt-package

jobs:
  build:
    name: Build ${{ matrix.arch }} ipk
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - mediatek-filogic
        version: [snapshot]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: innet8/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.version }}
          MODE: open
          DEPENDENCES: libev libopenssl libmbedtls zlib
          ADDR: ${{ env.REPO_URL }}
          BRANCH: ${{ env.REPO_BRANCH }}
          PKG: rtty
          
      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: "rtty*.ipk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}